/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tickets */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    category?: string;
                    channel?: string;
                    search?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tickets found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            tickets?: components["schemas"]["Ticket"][];
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create ticket */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        subject: string;
                        description?: string;
                        category?: string;
                        priority?: string;
                        channel?: string;
                        /** Format: uuid */
                        tenantId?: string;
                        /** Format: uuid */
                        unitId?: string;
                    };
                };
            };
            responses: {
                /** @description Ticket created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ticket?: components["schemas"]["Ticket"];
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tickets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ticket by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ticket found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ticket?: components["schemas"]["TicketWithMessages"];
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send message on a ticket (email) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        ticketId: string;
                        to: string[];
                        cc?: string[];
                        bcc?: string[];
                        subject: string;
                        text?: string;
                        html?: string;
                        attachments?: {
                            filename: string;
                            mimeType?: string;
                            contentBase64: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Message sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message?: components["schemas"]["Message"];
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contractors/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search contractors (external) */
        get: {
            parameters: {
                query?: {
                    category?: string;
                    term?: string;
                    location?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contractors found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            contractors?: components["schemas"]["Contractor"][];
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get signed upload URL for attachments */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Storage path to upload to */
                        path: string;
                        contentType: string;
                        /** @default attachments */
                        bucket?: string;
                    };
                };
            };
            responses: {
                /** @description Signed upload URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            signedUrl?: string;
                            token?: string;
                            bucket?: string;
                            path?: string;
                            contentType?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
                /** @description Error */
                default: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code?: string;
                message?: string;
                details?: unknown;
            };
        };
        Attachment: {
            id?: string;
            filename: string;
            mimeType?: string;
            sizeInBytes?: number;
            /** Format: uri */
            url?: string;
        };
        Message: {
            id?: string;
            ticketId?: string;
            /** @enum {string} */
            direction?: "INBOUND" | "OUTBOUND";
            /** @enum {string} */
            channel?: "EMAIL" | "WHATSAPP" | "SMS" | "INTERNAL";
            subject?: string | null;
            bodyText?: string | null;
            bodyHtml?: string | null;
            /** Format: date-time */
            sentAt?: string;
            attachments?: components["schemas"]["Attachment"][];
        };
        Ticket: {
            id: string;
            subject: string;
            description?: string | null;
            category: string;
            status: string;
            priority: string;
            channel: string;
            /** Format: date-time */
            openedAt: string;
            tenantId?: string | null;
            unitId?: string | null;
            latestMessageSnippet?: string | null;
        };
        TicketWithMessages: components["schemas"]["Ticket"] & {
            tenantName?: string | null;
            unitName?: string | null;
            messages?: components["schemas"]["Message"][];
        };
        Contractor: {
            id?: string;
            name?: string;
            phone?: string | null;
            email?: string | null;
            website?: string | null;
            rating?: number | null;
            reviewCount?: number | null;
            address?: string | null;
            source?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
